const teamPlayer = {
  GT:{  
    teamCode: "GT",
    teamColor: "linear-gradient(180deg, #1C1C1C 0%, #0B4973 100%)",
    player: [
      {
        id: "GT01",
        playerName: "Hardik Pandya",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2740.png",
        role: "All Rounder",
        wickets: "50",
        run: "1963",
        matches: "107",
      },
      {
        id: "GT02",
        playerName: "Rashid Khan",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2885.png",
        role: "Bowler",
        wickets: "112",
        run: "313",
        matches: "92",
      },
      {
        id: "GT03",
        playerName: "Rahul Tewatia",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1749.png",
        role: "Bowler",
        wickets: "32",
        run: "738",
        matches: "64",
      },
      {
        id: "GT04",
        playerName: "Abhinav Manohar",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20589.png",
        role: "Batter",
        wickets: "0",
        run: "108",
        matches: "8",
      },

      {
        id: "GT05",
        playerName: "David Miller",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/187.png",
        role: "Batter",
        wickets: "0",
        run: "2455",
        matches: "105",
      },
      {
        id: "GT06",
        playerName: "Rahmullah Gurbaz",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20625.png",
        role: "Batter",
        wickets: "0",
        run: "0",
        matches: "0",
      },

      {
        id: "GT07",
        playerName: "Shubham Gill",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3761.png",
        role: "Batter",
        wickets: "0",
        run: "1900",
        matches: "74",
      },
      {
        id: "GT08",
        playerName: "Mathew Wade",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/290.png",
        role: "Wicket-Keeper",
        wickets: "0",
        run: "179",
        matches: "13",
      },
      {
        id: "GT09",
        playerName: "Wriddhiman Saha",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/16.png",
        role: "Wicketkeeper-Batter",
        wickets: "0",
        run: "2427",
        matches: "144",
      },
      {
        id: "GT10",
        playerName: "Mohammad Sami",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/94.png",
        role: "Bowler",
        wickets: "99",
        run: "69",
        matches: "93",
      },
      {
        id: "GT11",
        playerName: "B.Sai Sudharsan",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20592.png",
        role: "All-Rounder",
        wickets: "0",
        run: "145",
        matches: "5",
      },
      {
        id: "GT12",
        playerName: "Darshan Nalkande",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/4447.png",
        role: "All-Rounder",
        wickets: "2",
        run: "0",
        matches: "2",
      },
      {
        id: "GT13",
        playerName: "Alzarri Joseph",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3098.png",
        role: "Bowler",
        wickets: "13",
        run: "20",
        matches: "12",
      },
  
      {
        id: "GT14",
        playerName: "Lockie Ferguson",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3729.png",
        role: "Bowler",
        wickets: "36",
        run: "67",
        matches: "35",
      },
      {
        id: "GT15",
        playerName: "Varun Aaron",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/61.png",
        role: "Bowler",
        wickets: "44",
        run: "50",
        matches: "52",
      },
    ],
  },

  CSK:{
    teamCode: "CSK",
    teamColor: "linear-gradient(180deg, #FCCA06 0%, #F25C19 100%)",
    player: [
      {
        id: "CSK01",
        playerName: "MS Dhoni",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "4978",
        matches: "234",
      },
      {
        id: "CSK02",
        playerName: "Devon Conway",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20572.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "252",
        matches: "7",
      },
      {
        id: "CSK03",
        playerName: "Robin Uthappa",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/127.png",
        role: "Batter",
        wickets: "0",
        run: "4952",
        matches: "205",
      },
      {
        id: "CSK04",
        playerName: "Ruturaj Gaikwad",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5443.png",
        role: "Batter",
        wickets: "0",
        run: "1207",
        matches: "36",
      },
      {
        id: "CSK05",
        playerName: "Subhranshu Senapati",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20574.png",
        role: "Batter",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "CSK06",
        playerName: "Amabati Rayudu",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/100.png",
        role: "Wicketkeeper-Batter",
        wickets: "0",
        run: "4190",
        matches: "188",
      },
      {
        id: "CSK07",
        playerName: "Shivam Dube",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5431.png",
        role: "All Rounder",
        wickets: "4",
        run: "688",
        matches: "35",
      },
      {
        id: "CSK08",
        playerName: "Narayan Jagadeesan",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/4942.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "73",
        matches: "7",
      },
      {
        id: "CSK09",
        playerName: "Moeen Ali",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1735.png",
        role: "All rounder",
        wickets: "24",
        run: "910",
        matches: "44",
      },
      {
        id: "CSK10",
        playerName: "Ravindra Jadeja",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/9.png",
        role: "All rounder",
        wickets: "132",
        run: "2502",
        matches: "210",
      },
      {
        id: "CSK11",
        playerName: "Rajvardhan Hangargekar",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20571.png",
        role: "Bowler",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "CSK12",
        playerName: "Chris Jordan",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1299.png",
        role: "Bowler",
        wickets: "27",
        run: "75",
        matches: "28",
      },
      {
        id: "CSK13",
        playerName: "Mahesh Theekshana",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20570.png",
        role: "Bowler",
        wickets: "12",
        run: "7",
        matches: "9",
      },
      {
        id: "CSK14",
        playerName: "Dwaine Pretorius",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20573.png",
        role: "Bowler",
        wickets: "6",
        run: "44",
        matches: "6",
      },
      {
        id: "CSK15",
        playerName: "Adam Milne",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/434.png",
        role: "Bowler",
        wickets: "7",
        run: "23",
        matches: "10",
      },
    ],
  },

  DC: {
    teamCode: "DC", 
    teamColor: "linear-gradient(180deg, #0078BC 0%, #17479E 100%)",
    player: [
      {
        id: "DC01",
        playerName: "Rishabh Pant",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2972.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "2838",
        matches: "98",
      },
      {
        id: "DC02",
        playerName: "Ashwin Hebbar",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/0.png",
        role: "Batter",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "DC03",
        playerName: "David Warner",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/170.png",
        role: "Batter",
        wickets: "0",
        run: "5881",
        matches: "162",
      },
      {
        id: "DC04",
        playerName: "Mandeep Singh",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/72.png",
        role: "All Rounder",
        wickets: "1",
        run: "1692",
        matches: "108",
      },
      {
        id: "DC05",
        playerName: "Prithvi Shaw",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3764.png",
        role: "Batter",
        wickets: "0",
        run: "1588",
        matches: "63",
      },
      {
        id: "DC06",
        playerName: "Rovman Powell",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3333.png",
        role: "Batter",
        wickets: "0",
        run: "250",
        matches: "14",
      },
      {
        id: "DC07",
        playerName: "K.S Bharat",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2734.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "199",
        matches: "10",
      },
      {
        id: "DC08",
        playerName: "Tim Seifert",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1619.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "26",
        matches: "3",
      },
      {
        id: "DC09",
        playerName: "Axar Patel",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1113.png",
        role: "All Rounder",
        wickets: "101",
        run: "1135",
        matches: "122",
      },
      {
        id: "DC10",
        playerName: "Kamlesh Nagarkoti",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3766.png",
        role: "Bowler",
        wickets: "5",
        run: "22",
        matches: "12",
      },
      {
        id: "DC11",
        playerName: "Lalit Yadav",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/6870.png",
        role: "All Rounder",
        wickets: "8",
        run: "229",
        matches: "19",
      },
      {
        id: "DC12",
        playerName: "Mitchell Marsh",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/221.png",
        role: "All Rounder",
        wickets: "24",
        run: "477",
        matches: "29",
      },
      {
        id: "DC13",
        playerName: "Pravin Dubey",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3188.png",
        role: "Bowler",
        wickets: "0",
        run: "7",
        matches: "3",
      },
      {
        id: "DC14",
        playerName: "Ripal Patel",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/17191.png",
        role: "Batter",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "DC15",
        playerName: "Sarfaraz Khan",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1564.png",
        role: "Batter",
        wickets: "0",
        run: "532",
        matches: "46",
      },
    ],
  },
  KKR:{
    teamCode: "KKR",
    teamColor: "linear-gradient(180deg, #3B215D 0%, #552792 100%)",
    player: [
      {
        id: "KKR01",
        playerName: "Shreyar Iyer",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1563.png",
        role: "Batter",
        wickets: "0",
        run: "2776",
        matches: "101",
      },
      {
        id: "KKR02",
        playerName: "Ajinkya Rahane",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/135.png",
        role: "Batter",
        wickets: "1",
        run: "4074",
        matches: "158",
      },
      {
        id: "KKR03",
        playerName: "Rinku Singh",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3830.png",
        role: "Batter",
        wickets: "0",
        run: "251",
        matches: "17",
      },
      {
        id: "KKR04",
        playerName: "Aaron Finch",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/167.png",
        role: "Batter",
        wickets: "1",
        run: "2091",
        matches: "92",
      },
      {
        id: "KKR05",
        playerName: "Abhijeet Tomar",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20580.png",
        role: "Batter",
        wickets: "0",
        run: "4",
        matches: "1",
      },
      {
        id: "KKR06",
        playerName: "Ramesh Kumar",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20582.png",
        role: "All Rounder",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "KKR07",
        playerName: "Pratham Singh",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20583.png",
        role: "Batter",
        wickets: "0",
        run: "0",
        matches: "0",
      },
      {
        id: "KKR08",
        playerName: "Sheldon Jackson",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1116.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "61",
        matches: "9",
      },
      {
        id: "KKR09",
        playerName: "Sam Billings",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2756.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "503",
        matches: "30",
      },
      {
        id: "KKR10",
        playerName: "Baba Indrajith",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20578.png",
        role: "Batter",
        wickets: "0",
        run: "21",
        matches: "3",
      },
      {
        id: "KKR11",
        playerName: "Pat Cummins",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/488.png",
        role: "Bowler",
        wickets: "45",
        run: "379",
        matches: "42",
      },
      {
        id: "KKR12",
        playerName: "Mohammad Nabi",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/618.png",
        role: "All Rounder",
        wickets: "13",
        run: "180",
        matches: "17",
      },
      {
        id: "KKR13",
        playerName: "Nitish Rana",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2738.png",
        role: "Batter",
        wickets: "7",
        run: "2181",
        matches: "91",
      },
      {
        id: "KKR14",
        playerName: "Shivam Mavi",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3779.png",
        role: "All Rounder",
        wickets: "30",
        run: "51",
        matches: "32",
      },
      {
        id: "KKR15",
        playerName: "Ankul Roy",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3774.png",
        role: "All Rounder",
        wickets: "2",
        run: "0",
        matches: "2",
      },
    ],
  },
  LSG:{
    teamCode: "LSG",
    teamColor:"linear-gradient(180deg, #A72056 0%, #FFCC00 100%)",
    player:[
        {
        id: "LSG01",
        playerName: "KL Rahul",
        profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1125.png",
        role: "Wicketkeeper Batter",
        wickets: "0",
        run: "3889",
        matches: "109",
        },
        {
            id: "LSG02",
            playerName: "Evin Lewis",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/872.png",
            role: "Batter",
            wickets: "0",
            run: "654",
            matches: "27",
        },
        {
            id: "LSG03",
            playerName: "Manan Vohra",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1085.png",
            role: "Batter",
            wickets: "0",
            run: "1073",
            matches: "55",
        },
        {
            id: "LSG04",
            playerName: "Manish Pandey",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/123.png",
            role: "Batter",
            wickets: "0",
            run: "3648",
            matches: "160",
        },
        {
            id: "LSG05",
            playerName: "Quinton de Kock",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/834.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "2764",
            matches: "92",
        },
        {
            id: "LSG06",
            playerName: "Ayush Badoni",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20586.png",
            role: "Bowler",
            wickets: "0",
            run: "161",
            matches: "13",
        },
        {
            id: "LSG07",
            playerName: "Deepak Hooda",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1556.png",
            role: "Bowler",
            wickets: "10",
            run: "1236",
            matches: "95",
        },
        {
            id: "LSG08",
            playerName: "Jason Holder",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1075.png",
            role: "All Rounder",
            wickets: "49",
            run: "247",
            matches: "38",
        },
        {
            id: "LSG09",
            playerName: "Krishnappa Gowtham",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3834.png",
            role: "All Rounder",
            wickets: "18",
            run: "186",
            matches: "28", 
        },
        {
            id: "LSG10",
            playerName: "Karan Sharma",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20588.png",
            role: "All Rounder",
            wickets: "18",
            run: "186",
            matches: "28", 
        },
        {
            id: "LSG11",
            playerName: "Krunal Pandya",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3183.png",
            role: "All Rounder",
            wickets: "61",
            run: "1326",
            matches: "98",
        },
        {
            id: "LSG12",
            playerName: "Kyle Mayers",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20587.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "LSG13",
            playerName: "Marcus Stoinis",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/964.png",
            role: "All Rounder",
            wickets: "34",
            run: "1070",
            matches: "67",
        },
        {
            id: "LSG14",
            playerName: "Ankit Rajpoot",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1106.png",
            role: "Bowler",
            wickets: "24",
            run: "26",
            matches: "29", 
        },
        {
            id: "LSG15",
            playerName: "Avesh Khan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1561.png",
            role: "Bowler",
            wickets: "47",
            run: "31",
            matches: "38", 
        },
    ]
  },
 MI: {
    teamCode: "MI",
    teamColor:"linear-gradient(180deg, #006CB7 0%, #003B7A 100%)",
    player:[
        {
            id: "MI01",
            playerName: "Rohit Sharma",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/107.png",
            role: "Batter",
            wickets: "15",
            run: "5879",
            matches: "227",
        },
        {
            id: "MI02",
            playerName: "Anmolpreet Singh",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2965.png",
            role: "Batter",
            wickets: "0",
            run: "29",
            matches: "3",
        },
        {
            id: "MI03",
            playerName: "Dewald Brevis",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20593.png",
            role: "Batter",
            wickets: "1",
            run: "161",
            matches: "7",
        },
        {
            id: "MI04",
            playerName: "Rahul Buddhi",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20597.png",
            role: "Batter",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "MI05",
            playerName: "Suryakumar Yadav",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/108.png",
            role: "Batter",
            wickets: "0",
            run: "2644",
            matches: "123",
        },
        {
            id: "MI06",
            playerName: "Aryan Juyal",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20596.png",
            role: "Wicket keeper",
            wickets: "0",
            run: "2644",
            matches: "123",
        },
        {
            id: "MI07",
            playerName: "Ishan Kishan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2975.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "1870",
            matches: "75",   
        },
        {
            id: "MI08",
            playerName: "Ishan Kishan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2975.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "1870",
            matches: "75",   
        },
        {
            id: "MI09",
            playerName: "Arjun Tendulkar",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/10244.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",   
        },
        {
            id: "MI10",
            playerName: "Daniel Sams",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/4649.png",
            role: "All Rounder",
            wickets: "14",
            run: "44",
            matches: "16", 
        },
        {
            id: "MI11",
            playerName: "Fabian Allen",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1707.png",
            role: "All Rounder",
            wickets: "2",
            run: "14",
            matches: "5",
        },
        {
            id: "MI12",
            playerName: "Hrithik Shokeen",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20598.png",
            role: "Bowler",
            wickets: "2",
            run: "46",
            matches: "5",
        },
        {
            id: "MI13",
            playerName: "Mohd.Ashad Khan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20599.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "MI14",
            playerName: "Kieron Pollard",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/210.png",
            role: "All Rounder",
            wickets: "69",
            run: "3412",
            matches: "189",
        },
        {
            id: "MI15",
            playerName: "Jashprit Bumrah",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1124.png",
            role: "Bowler",
            wickets: "145",
            run: "57",
            matches: "120",
        }, 
    ]
  },
  PBKS:{
    teamCode: "PBKS",
    teamColor: "linear-gradient(180deg, #D71920 0%, #84171B 100%)",
    player:[
        {
            id: "PBKS01",
            playerName: "Mayank Agrawal",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/158.png",
            role: "Batter",
            wickets: "0",
            run: "2327",
            matches: "113",
        },
        {
            id: "PBKS02",
            playerName: "Bhanuka Rajapaksha",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20604.png",
            role: "Batter",
            wickets: "0",
            run: "206",
            matches: "9",
        },
        {
            id: "PBKS03",
            playerName: "Shikhar Dhawan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/41.png",
            role: "Batter",
            wickets: "4",
            run: "6244",
            matches: "206",
        },
        {
            id: "PBKS04",
            playerName: "Jitesh Sharma",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3185.png",
            role: "Wicket keeper",
            wickets: "0",
            run: "234",
            matches: "12",
        },
        {
            id: "PBKS05",
            playerName: "Jonny Bairstow",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/506.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "1291",
            matches: "39",
        },
        {
            id: "PBKS06",
            playerName: "Prabhsimran Singh",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5436.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "64",
            matches: "6",
        },
        {
            id: "PBKS07",
            playerName: "Ansh Patel",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20608.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "PBKS08",
            playerName: "Atharva Taide",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20603.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "PBKS09",
            playerName: "Benny Howell",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20605.png",
            role: "All Rounder",
            wickets: "0",
            run: "0",
            matches: "0",
        },
        {
            id: "PBKS10",
            playerName: "Harpreet Brar",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5441.png",
            role: "Bowler",
            wickets: "9",
            run: "106",
            matches: "15",
        },
        {
            id: "PBKS11",
            playerName: "Liam Livingstone",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3644.png",
            role: "Batter",
            wickets: "6",
            run: "549",
            matches: "23",
        },
        {
            id: "PBKS12",
            playerName: "Odean Smith",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20600.png",
            role: "Bowler",
            wickets: "6",
            run: "51",
            matches: "6",
        },
        {
            id: "PBKS13",
            playerName: "Prerak Mankad",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20602.png",
            role: "Batter",
            wickets: "0",
            run: "4",
            matches: "1",
        },
        {
            id: "PBKS14",
            playerName: "Shahrukh Khan",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/7779.png",
            role: "Batter",
            wickets: "0",
            run: "270",
            matches: "19",
        },
        {
            id: "PBKS15",
            playerName: "Kagiso Rabada",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1664.png",
            role: "Bowler",
            wickets: "99",
            run: "186",
            matches: "63",
        },
       
    ]
  },
  RR: {
    teamCode: "RR",
    teamColor: " linear-gradient(180deg, #EA1A85 0%, #001D48 100%)",
    player:[
        {
            id: "RR01",
            playerName: "Sanju Samson",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/258.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run: "3526",
            matches: "138",
        },
        {
            id: "RR02",
            playerName: "Devdutt Padikkal",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5430.png",
            role: "Batter",
            wickets: "0",
            run: "1260",
            matches: "46",
        },
        {
            id: "RR03",
            playerName: "Jos Buttler",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/509.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"2831",
            matches: "82",
        },
        {
            id: "RR04",
            playerName: "Karun Nair",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/276.png",
            role: "All Rounder",
            wickets: "0",
            run:"1496",
            matches: "76",
        },
        {
            id: "RR05",
            playerName: "Rassie Van Der Dussen",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20619.png",
            role: "Batter",
            wickets: "0",
            run:"22",
            matches: "3",
        },
        {
            id: "RR06",
            playerName: "Shimron Hetmyer",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1705.png",
            role: "Batter",
            wickets: "0",
            run:"831",
            matches: "46",
        },
        {
            id: "RR07",
            playerName: "Yashasvi Jaiswal",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/13538.png",
            role: "Batter",
            wickets: "0",
            run:"547",
            matches: "23",
        },
        {
            id: "RR08",
            playerName: "Dhruv Jurel",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20620.png",
            role: "Wicketkeeper",
            wickets: "0",
            run:"0",
            matches: "0",
        },
        {
            id: "RR09",
            playerName: "Anunay Singh",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20622.png",
            role: "All rounder",
            wickets: "0",
            run:"0",
            matches: "0",
        },
        {
            id: "RR10",
            playerName: "Daryl Mitchell",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20617.png",
            role: "All rounder",
            wickets: "0",
            run:"33",
            matches: "2",
        },
        {
            id: "RR11",
            playerName: "James Neesham",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20615.png",
            role: "Bowler",
            wickets: "8",
            run:"92",
            matches: "14",
        },
        {
            id: "RR12",
            playerName: "R. Ashwin",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/8.png",
            role: "All Rounder",
            wickets: "157",
            run:"647",
            matches: "184",
        },
        {
            id: "RR13",
            playerName: "Riyan Parag",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/4445.png",
            role: "Batter",
            wickets: "4",
            run:"522",
            matches: "47",
        },
        {
            id: "RR14",
            playerName: "Shubham Garhwal",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20621.png",
            role: "Bowler",
            wickets: "0",
            run:"0",
            matches: "0",
        },
        {
            id: "RR15",
            playerName: "Obed McCoy",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20618.png",
            role: "Bowler",
            wickets: "11",
            run:"8",
            matches: "7",
        },
    ]
  },
  RCB: {
    teamCode: "RCB",
    teamColor: "linear-gradient(180deg, #6A6A6A 0%, #1C1C1C 100%)",
    player:[
        {
            id: "RCB01",
            playerName: "Faf du Plessis",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/24.png",
            role: "Batter",
            wickets: "0",
            run:"3403",
            matches: "116",
        },
        {
            id: "RCB02",
            playerName: "Finn Allen",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3020.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"0",
            matches: "0",
        },
        {
            id: "RCB03",
            playerName: "Rajat Patidar",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5471.png",
            role: "Batter",
            wickets: "0",
            run:"404",
            matches: "12",
        },
        {
            id: "RCB04",
            playerName: "Virat Kohli",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/164.png",
            role: "Batter",
            wickets: "4",
            run:"6624",
            matches: "223",
        },
        {
            id: "RCB05",
            playerName: "Anuj Rawat",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/10788.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"129",
            matches: "10",
        },
        {
            id: "RCB06",
            playerName: "Dinesh Karthik",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/102.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"4376",
            matches: "229",
        },
        {
            id: "RCB07",
            playerName: "Luvnith Sisodia",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20613.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"0",
            matches: "0",
        },
        {
            id: "RCB08",
            playerName: "David Willey",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2758.png",
            role: "All Rounder",
            wickets: "3",
            run:"18",
            matches: "7",
        },
        {
            
            id: "RCB09",
            playerName: "Glen Maxwell",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/282.png",
            role: "All Rounder",
            wickets: "28",
            run:"2319",
            matches: "110",
        },
        {
            id: "RCB10",
            playerName: "Harshal Patel",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/157.png",
            role: "Bowler",
            wickets: "97",
            run:"230",
            matches: "78",
        },
        {
            id: "RCB11",
            playerName: "Mahipal Lomar",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2970.png",
            role: "All Rounder",
            wickets: "1",
            run:"267",
            matches: "18",
        },
        {
            id: "RCB12",
            playerName: "Shahbaz Ahamad",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/13803.png",
            role: "Bowler",
            wickets: "13",
            run:"279",
            matches: "29",
        },
        {
            id: "RCB13",
            playerName: "Sherfane Rutherford",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5396.png",
            role: "Batter",
            wickets: "1",
            run:"106",
            matches: "10",
        },
        {
            id: "RCB14",
            playerName: "Suyash S Prabhudessai",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/7002.png",
            role: "Batter",
            wickets: "0",
            run:"67",
            matches: "5",
        },
        {
            id: "RCB15",
            playerName: "Akash Deep",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/14800.png",
            role: "Bowler",
            wickets: "5",
            run:"0",
            matches: "5",
        },
    ]
  },
  SRH:{
    teamCode: "SRH",
    teamColor:"linear-gradient(180deg, #F26522 0%, #ED1A37 100%)",
    player:[
        {
            id: "SRH01",
            playerName: "Kane Williamson",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/440.png",
            role: "Batter",
            wickets: "0",
            run:"2101",
            matches: "76",
        },
        {
            id: "SRH02",
            playerName: "Abdul Samad",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/19352.png",
            role: "Batter",
            wickets: "2",
            run:"226",
            matches: "25",
        },
        {
            id: "SRH03",
            playerName: "Aiden Markam",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1667.png",
            role: "Batter",
            wickets: "1",
            run:"527",
            matches: "20",
        },
        {
            id: "SRH04",
            playerName: "Priyam Garg",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3775.png",
            role: "Batter",
            wickets: "0",
            run:"251",
            matches: "21",
        },
        {
            id: "SRH05",
            playerName: "Ravikumar Samarth",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20611.png",
            role: "Batter",
            wickets: "0",
            run:"0",
            matches: "0", 
        },
        {
            id: "SRH06",
            playerName: "Rahul Tripathi",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3838.png",
            role: "Batter",
            wickets: "0",
            run:"1798",
            matches: "76",
        },
        {
            id: "SRH07",
            playerName: "Glenn Phillips",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3027.png",
            role: "Wicketkeeper Batter",
            wickets: "1",
            run:"26",
            matches: "3",
        },
        {
            id: "SRH08",
            playerName: "Nicholas Pooran",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1703.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"912",
            matches: "47",
        },
        {
            id: "SRH09",
            playerName: "Vishnu Vinod",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/4305.png",
            role: "Wicketkeeper Batter",
            wickets: "0",
            run:"19",
            matches: "3",
        },
        {
            id: "SRH10",
            playerName: "Abhishek Sharma",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3760.png",
            role: "All Rounder",
            wickets: "7",
            run:"667",
            matches: "36",
        },
        {
            id: "SRH11",
            playerName: "Marco Jansen",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/17068.png",
            role: "All Rounder",
            wickets: "9",
            run:"9",
            matches: "10",
        },
        {
            id: "SRH12",
            playerName: "Shashank Singh",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3261.png",
            role: "Batter",
            wickets: "0",
            run:"69",
            matches: "10",
        },
        {
            id: "SRH13",
            playerName: "Romario Shepherd",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20609.png",
            role: "All Rounder",
            wickets: "3",
            run:"58",
            matches: "3",
        },
        {
            id: "SRH14",
            playerName: "Bhuvaneshwar Kumar",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/116.png",
            role: "Bowler",
            wickets: "154",
            run:"241",
            matches: "146",
        },
        {
            id: "SRH15",
            playerName: "Fazalhaq Farooqi",
            profile: "https://assets.iplt20.com/ipl/IPLHeadshot2022/20610.png",
            role: "Bowler",
            wickets: "2",
            run:"2",
            matches: "3",
        },
    ]
  }
};

export default teamPlayer 
